apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.api.deployment}}"
spec:
  replicas: {{ default 3 .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: "{{.Values.api.name}}"
        version: "{{.Values.api.versionLabel}}"
    spec:
      containers:
      - name: "{{.Values.api.name}}"
        image: "{{.Values.api.image}}:{{.Values.api.imageTag}}"
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.api.name}}"
  labels:
    app: "{{.Values.api.name}}"
spec:
  type: "{{.Values.api.serviceType}}"
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: "{{.Values.api.name}}"